### ISSUE TITLE
1.10.2 Scanning not seeing vanilla ores

### ISSUE THREAD

**Issue by Saereth** [way2muchnoise/JustEnoughResources#108]
I ran a 3k chunk scan and its not showing an vanilla ores like gold/iron. I put down a digital miner to verify the ore was there and it is.

command I'm using is /profile 3000, set DIY to true and put the file in the folder. Manually looking a tthe json file generated shows no vanilla ores. 

https://hastebin.com/iqutuyisof.json

update: I changed it to /profile 3000 all and let it scan all the dimensions, it does find vanilla ores in deep dark and aroma mining worlds, just not overworld it seems.

**Comment by MisterObvious25** [comment]
I have the same issue but not only with vanilla ores, i use wtf-expedition to generate all the ores to avoid duplicates, but somehow everything it generates is not showing up in the profile(including vanilla ore)

**Comment by Williamhb** [comment]
I have the same problem, im using RTG, BOP, and harvest festival (witch seams to change the name of the overworld to "seasons?? ehh ok)", but anyway. 

When i set DIY data to true, and then do a "/profile 10000 all" I will see vanilla ore's in all dimensions, except the overworld

When i set DIY data to false, and then do a "/profile 10000 all" I will see mods ore's in all dimensions, **including** the overworld, but not vanilla.

maybe there's something missing in either code of DIY data = false or true

i hope this helps someone. peace

**Comment by way2muchnoise** [comment]
I don't know which exact combination of factors is causing this. The profiling works fine in a vanilla world, and for example it also works in the Age of Engineering modpack. So if anyone can pin point a 100% reproducible case, feel free to make a new issue.

@Williamhb I can't change anything about that rename of the world to seasons, this is because I use the world dimension name and it seems like harvest festival is changing that.
