### ISSUE TITLE
Crash upon reloading resourcepacks when Quark installed

### ISSUE THREAD

**Issue by juliand665** [way2muchnoise/JustEnoughResources#151]
This was a tough one to identify, but I've reduced the crash down to JER and Quark (and their dependencies, JEI and AutoRegLib respectively). When pressing F3+T in-game to reload resourcepacks (which some people have to do to fix sound issues), the game freezes.

I've pinpointed the crash down to the moment JEI registers the plugin `jeresources.jei.JEIConfig`, after which the game just freezes. (Once you force quit it, a message comes through that it's shutting down the integrated server, so the logging isn't what's breaking.) I've attached the logs, although I doubt they'll be very helpful.

In these logs, I added some missing model files to Quark in an attempt to reduce the noise caused by the errors:
[debug.log](https://github.com/way2muchnoise/JustEnoughResources/files/2185013/debug.log)
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/2185014/latest.log)

These logs are with the mods as they come:
[debug.log](https://github.com/way2muchnoise/JustEnoughResources/files/2185024/debug.log)
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/2185025/latest.log)

The versions of the mods in question are:
JEI 1.12.2-4.11.0.202
JER 1.12.2-0.8.5.27
AutoRegLib 1.3-18
Quark r1.4-125

I'm reporting the issue here rather than in Quark because it seems like it's JER's code that's crashing; not Quark's (although Quark does have a coremod component). I'm betting on an infinite loop somewhere :)

**Comment by Hallo89** [comment]
I have also just finished tracking this down, so I might as well give some extra information, useful hopefully:
-Quark itself is causing the crash together with JER, meaning it is not AutoRegLib.
-After registering the above mentioned `jeresources.jei.JEIConfig`, Forge tries and fails continuously `Gathering id map for writing to world save <world name>` until it is shut down manually;
```
[22:06:18] [main/DEBUG] [jei]: Registering plugin: jeresources.jei.JEIConfig ...
[22:06:42] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save New World
[22:07:27] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save New World
[22:08:12] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save New World
[22:08:57] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save New World
[22:09:42] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save New World
...
```
-This is actually no new bug at all. Since the release of those 2 mods for 1.12.2, this bug has been present. I did not report it because, well, good question. I'm not good at reporting bugs and then I forgot it for a long time. I'm sorry.
I hope this helps, I just didn't want to let my past hours vanish lol

**Comment by way2muchnoise** [comment]
Is this still an issue?

**Comment by juliand665** [comment]
Yup. Just reproduced with:

- JER 1.12.2-0.8.5.27
- JEI 1.12.2-4.15.0.268
- Quark r1.5-146
- AutoRegLib 1.3-26

**Comment by way2muchnoise** [comment]
Worked for me in dev with:

- JER 0.9.2
- JEI 4.15.0
- Quark r1.5-158
- AutoRegLib 1.3-30

Can I consider this fixed?

**Comment by Hallo89** [comment]
Just checked as well, seems to be fixed
