### ISSUE TITLE
[1.12.2] Graphical Issue with Mob Drops when using certain GUI Scales

### ISSUE THREAD

**Issue by tetra8** [way2muchnoise/JustEnoughResources#155]
When viewing mob drops using a small or normal GUI scale, mobs shown are either largely or entirely made unviewable. This issue was present for me when using Forge 14.23.4.2747, JEI 4.11.0.206, and JER 0.8.8.487 (and at least a few combinations of previous versions as well).

**Small**
![small](https://user-images.githubusercontent.com/42025133/43569297-99c3509a-9669-11e8-842c-0dbbc4781a63.png)

**Normal**
![normal](https://user-images.githubusercontent.com/42025133/43569298-99f98d9a-9669-11e8-83d1-64575b5ae2e0.png)

**Large**
![large](https://user-images.githubusercontent.com/42025133/43569299-9a30855c-9669-11e8-8104-a48105866310.png)

**Auto**
![auto](https://user-images.githubusercontent.com/42025133/43569296-997eb516-9669-11e8-8ce9-11d3bd7e5b5c.png)

**Comment by beanaboston** [comment]
Hello! throwing my comment in here saying i'm having the same problem with version 1.12.2-4.11.0.206 of JEI, version 1.12.2-0.8.9.48 of JER, and version 14.23.4.2749 of forge.

large and smaller:
![2018-08-11_13 40 42](https://user-images.githubusercontent.com/32643374/43994510-3649d458-9d6c-11e8-8a5c-4a8326ce6784.png)

auto:
![2018-08-11_13 40 32](https://user-images.githubusercontent.com/32643374/43994512-3cdfcd68-9d6c-11e8-9e8d-298e661cd03d.png)


I'm guessing it only works on auto for me because my monitor is higher resolution and so the large is a decent amount smaller than auto. Still has space for 2 entries, whereas tetra's on large it only has space for 1. (wasn't in fullscreen that my affect is as well)

Seems like it breaks when there is space for 2 entries. No matter if there actually is 2 entries or not.

**Comment by beanaboston** [comment]
Oh right! forget to say it also happens with villager trades. The picture of the villager has the same problem. Assuming that it is the same way as the mob pictures. haven't done real testing.
