### ISSUE TITLE
[1.14.4] Upgrade Aquatic causes casting issue with projectile/special attack entity being cast to LivingEntity

### ISSUE THREAD

**Issue by noobanidus** [way2muchnoise/JustEnoughResources#223]
[Crash report here](https://gist.github.com/noobanidus/984a48701c888628837023e47bfe708c).

I haven't the time to look into it extensively myself but I'm presuming that some type of loot table is being registered or instantiated for this wave entity and thus JER is presuming it is a living entity.

You might need to check inheritance before casting here.

**Comment by noobanidus** [comment]
[The same also happens with Paraglider](https://gist.github.com/noobanidus/6502127ceafb29d19296ff9bac9e3acb).

**Comment by SmellyModder** [comment]
I can comment on this as well. The `add()` methods in `MobTableBuilder` always use `LivingEntity` without even checking if its an instance of it. Right now it cycles through all the registered entities, and this doesn't exactly work well since the entities won't always be an instance of `LivingEntity` of course, but I did also notice there is a check to tell if the entity is in the `MISC` classification before calling the `add()` method; this works fine in Vanilla, but some other modders might not realize what impact that really has.

**Comment by noobanidus** [comment]
Looking at it further, I don't understand why you're making the assumption that every non-MISC will be `EntityType<LivingEntity>`, especially when you are specifically using generics to cast to it. If you used `EntityType<?>` instead you could do:

```Entity LIvingEntity = entityType.create(world)
if (LivingEntity instanceof LivingEntity) {
}
```

The only other use I can see of this is with sheep specifically, so I'm guessing if you just split out the `add` which takes an `EntityPropertySetter<T>` into its own thing specifically for sheep, you could (with a little duplication) have both pretty easily -- and not crash when things aren't descended from LivingEntity.
