### ISSUE TITLE
Profiler hangs on Erebus, project ozone 3 pack

### ISSUE THREAD

**Issue by dumfist** [way2muchnoise/JustEnoughResources#233]
Profiler gets through dimension 0, 1, 5, 6, 7, 8, then gets to dimension 9, the erebus, and stops progressing. been waiting 15 minutes, no progress. Also, I am unable to interact with anything at this time. No chat commands work, no opening chests, etc. The game is pretty much frozen without actually being frozen.
![image](https://user-images.githubusercontent.com/64173629/80042794-8e5b6700-84c5-11ea-987c-1f84c342d477.png)

**Comment by jovlajo** [comment]
I have the same problem, it stops after 200 chunks from the erebus dimension for me.

**Comment by iopredman** [comment]
I reproduced this. Saw a similar error where the memory seemed to be full. No chunks would load and no new commands could be executed, and these are the relevant lines from the log:

[19:31:42] [Server thread/ERROR]: Chunk finished generating without Forge population being triggered (dimension 66). This is a bug with the dimension - please report this to the dimension's author. Recurrent Complex will proceed to generate in compatibility mode.
[19:31:42] [Client thread/INFO]: [CHAT] [Dim 66: EREBUS] Started profiling
[19:31:44] [Server thread/INFO]: Detected void dimension, adding to blacklist: 66

Seems to be caused by recurrent complex. Maybe it is causing cascading worldgen? I will try to load a world with the recurrent complex disabled and see if the issue persists.

Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Versions:
The Erebus: 1.0.31
Recurrent Complex: 1.4.8.2
JER: 0.9.2.60

Full Log: https://drive.google.com/file/d/1T4moajz-pkDI76TLqw5WV6usmV6i2ii6/view?usp=sharing

**Comment by iopredman** [comment]
Nope. Disabling Recurrent Complex and attempting to run "JER_profile 1000 all" now immediately causes a crash.

Log: https://drive.google.com/file/d/1dydMgosGhQJJP6xY9diUYPbuDsXpXUcs/view?usp=sharing
Crash Report: https://drive.google.com/file/d/1qTLNQu9RRsKh7PFGahBDe65KnU1zEwrO/view?usp=sharing

Don't know where to go from here.

**Comment by way2muchnoise** [comment]
You can always add dimension to the blacklist config of JER to avoid scanning them. It could be anything in these large packs and the scanning is not the most stable nor efficient feature of JER :P
