### ISSUE TITLE
[1.16] Issue when building mob view (Related to attributes on mob ai)

### ISSUE THREAD

**Issue by NillerMedDild** [way2muchnoise/JustEnoughResources#247]
Hi!

The scale/size of the Mob Drops JEI tab is slightly incorrect in `JustEnoughResources-1.16.1-0.11.0.81`

![billede](https://user-images.githubusercontent.com/21295394/88466129-8f87a000-cec9-11ea-8ef3-87aaa4081130.png)

**Comment by way2muchnoise** [comment]
Can you reproduce this with just JER (and JEI) installed? Or is this a cross mod issue? Please try to narrow down the conflicting mod(s), if so.

**Comment by NillerMedDild** [comment]
I cannot reproduce this with `JustEnoughResources-1.16.1-0.11.1.93` - Now there's no Mob Drops JEI section at all. Will try to find time to reproduce with just JEI and JER.

**Comment by way2muchnoise** [comment]
Hmmm, there have been some update by @RedstoneDubstep  to the mob drops. Maybe something broke?

**Comment by NillerMedDild** [comment]
Hmm, it did not, mod conflict, neither of these issues appear with just JEI and JER.

**Comment by way2muchnoise** [comment]
@NillerMedDild to narrow this down I would start looking at either mods adding a lot of mobs or changing mob drops/behaviour.

**Comment by NillerMedDild** [comment]
Found this in my latest.log, looks related: https://gist.github.com/NillerMedDild/d687e2a0529732e91a8699c7364d8a4d
It points to Abnormals Core

**Comment by way2muchnoise** [comment]
See crash report of @NillerMedDild 

```
java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.follow_range
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233810_d_(SourceFile:22) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233804_a_(SourceFile:28) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1728) ~[?:?]
```

**Comment by RedstoneDubstep** [comment]
Huh, I've been mentioned some time ago as it seems, and yes, I found something out about that bug (if this issue is still about the broken size of the mob drop tab):
I've experienced the same bug when the content of the view was offset or even not visible with some (but not all) mobs, and I think commenting out this line and the 5 below (https://github.com/way2muchnoise/JustEnoughResources/blob/master/src/main/java/jeresources/compatibility/minecraft/MinecraftCompat.java#L57).
These lines were - again - used for mob rendering, but because it is disabled (or because 1.16, idk) the texts were affected by them.
