### ISSUE TITLE
Cannot join servers with versions 123+ of JER

### ISSUE THREAD

**Issue by NillerMedDild** [way2muchnoise/JustEnoughResources#305]
Joining a server that has `JustEnoughResources-1.16.5-0.12.1.127` results in the player being kicked with the messaeg `Internal Server Error`. Reverting to `JustEnoughResources-1.16.5-0.12.1.122` resolves the issue.

Last part of the server log: https://gist.github.com/NillerMedDild/5ef3d47739020d921fe363723da833e1

**Comment by GreninjaSan** [comment]
We got the same issue an un upcoming modpack. We confirm the issue.

**Comment by twoworlds** [comment]
Can confirm this behaviour, we have the same problem. Reverting to .122 resolves the problem.

**Comment by Darkmega18** [comment]
also had this issue.

**Comment by CoercionX** [comment]
For me it only happens to OP'ed players (127). Brand new server build with only JEI and JER (JEI alone, no issue). Any survival player can play, log out and in, but as soon as you OP them, there in no broadcasted message, and on the server console I noticed it says:
"An unexpected error occurred trying to execute that command" instead of saying player has been op'ed.
They still retain OP though, but next time they try to login, and from then on, Internal Server Error. I have to delete my ops.json file on the server, restart it, then they can get back on (with no op).

**Comment by Angelic-System** [comment]
Same here

**Comment by glindsey** [comment]
Gonna add my +1 to this thread. Reverting to v122 resolved the issue.

**Comment by Nathan-Lane** [comment]
+1

**Comment by ModernGamingWorld** [comment]
Same here

**Comment by Kaleidio** [comment]
The issue was caused by the following commit#a6286af

when moving the api into the new folder, you broke quite a few mods that access this api as they do not acknowledge the directory changes.  the one in major question is FTB Library and the FTB Ranks mod, which uses the ranking system to lock certain je-suite features from certain players.

here's the log file in question: https://pastebin.com/EahrJrBQ

**Comment by Kaleidio** [comment]
The bug seems to be mostly surrounding an issue where DEDICATED SERVER is invalid for some methods used.

**Comment by Kaleidio** [comment]
https://github.com/way2muchnoise/JustEnoughResources/commit/601341dfbc7905a0dfec20ac482e07c895f39663

this commit here is at fault.  the mods using the api cause this to kick the player.

**Comment by Kaleidio** [comment]
to all participating in this thread, you can see that the commit is unfinished, that the implementation "will be done later"

because of this I fear way2muchnoise will be ignoring this issue until he has finished implementation.  stay downgraded to 122 (the builds get posted to curse automatically anyway) until further notice.

**Comment by Darkmega18** [comment]
> 
> 
> to all participating in this thread, you can see that the commit is unfinished, that the implementation "will be done later"
> 
> because of this I fear @way2muchnoise will be ignoring this issue until they have finished implementation. stay downgraded to 122 (the builds get posted to curse automatically anyway) until further notice.

![image](https://user-images.githubusercontent.com/8104689/128811387-103ae976-581e-49a9-8d9c-bddcce7eb495.png)

**Comment by Wedge1453** [comment]
either downgrading the mod on the server side or completly removing it (you can keep the latest version on client) solves the issue for me.
