### ISSUE TITLE
Some mob drops missing.

### ISSUE THREAD

**Issue by ExperimentCode3** [way2muchnoise/JustEnoughResources#64]
I noticed that in the mob drops section of JER zombies don't show that they drop potatoes or iron ingots.
![image](https://cloud.githubusercontent.com/assets/9259565/15341402/71568246-1c5c-11e6-969a-ed124d12d58b.png)

Also, not all the sheep are noted as dropping mutton.

![image](https://cloud.githubusercontent.com/assets/9259565/15341446/b491098c-1c5c-11e6-8c24-8125f6a2ac5d.png)

![image](https://cloud.githubusercontent.com/assets/9259565/15341422/92238816-1c5c-11e6-92a8-8b9ddef4b1f3.png)

And this sheep isn't noted as dropping wool.

![image](https://cloud.githubusercontent.com/assets/9259565/15341430/9d09452c-1c5c-11e6-9b00-69bad3c64191.png)

I have found that most of the mobs in the game don't have proper mob drops labeled. I hope that this report  helps this mod!

Here is a log in case there is something there that can help. 

[fml-client-latest (2).txt](https://github.com/way2muchnoise/JustEnoughResources/files/269274/fml-client-latest.2.txt)

**Comment by way2muchnoise** [comment]
It seems like it got worse since 1.10, see #75

**Comment by P3pp3rF1y** [comment]
When debugging code it looks like this is caused by following line https://github.com/way2muchnoise/JustEnoughResources/blob/master/src/main/java/jeresources/api/drop/LootDrop.java#L71 
Basically sometimes two different drops get the same sortIndex assigned and then the TreeSet they are being added to will overwrite the current node's value instead of adding new node to the tree.

I guess adding comparison of item names to the compareTo method in addition to sortIndexes should solve this issue.

**Comment by way2muchnoise** [comment]
Thx, for investigating this @P3pp3rF1y. I'll try and see what is going wrong. Most of that indexing is legacy code written by @hilburn IIRC
